import type { CSSProperties } from 'react';

export const testPlanStyles = {
  studioRoot: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    minHeight: 0,
    background: 'linear-gradient(180deg, var(--surface-tertiary) 0%, var(--surface-secondary) 120px)',
  } satisfies CSSProperties,
  studioToolbar: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    padding: '10px 16px',
    borderBottom: '1px solid var(--border-subtle)',
    backgroundColor: 'var(--surface-primary)',
    flexShrink: 0,
    flexWrap: 'wrap',
  } satisfies CSSProperties,
  demoBadge: {
    fontSize: 10,
    fontWeight: 700,
    padding: '3px 8px',
    borderRadius: 999,
    backgroundColor: 'var(--status-warning-bg)',
    color: 'var(--status-warning)',
    letterSpacing: '0.3px',
  } satisfies CSSProperties,
  bodyRow: {
    display: 'flex',
    flex: 1,
    minHeight: 0,
    overflow: 'hidden',
  } satisfies CSSProperties,
  timelineTrack: {
    flex: 1,
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column',
    minHeight: 0,
    backgroundColor: 'var(--bg-secondary)',
    borderLeft: '1px solid var(--border-subtle)',
  } satisfies CSSProperties,
  timelineScroll: {
    flex: 1,
    overflow: 'auto',
    padding: '20px 24px 32px',
    minHeight: 0,
  } satisfies CSSProperties,
  drawerOverlay: {
    position: 'fixed',
    left: 252,
    right: 0,
    bottom: 0,
    height: '46vh',
    backgroundColor: 'var(--surface-primary)',
    borderTop: '2px solid var(--accent-primary)',
    boxShadow: '0 -12px 40px rgba(0,0,0,0.12)',
    display: 'flex',
    flexDirection: 'column',
    zIndex: 50,
    animation: 'slideUp 0.25s ease',
  } satisfies CSSProperties,
};
