app:
  debug: true
  host: 0.0.0.0
  port: 8801
  service_name: dmlv4-backend_dev
  cors_origins:
  - '*'
  dev_bypass_auth: true
  dev_user_id: dev_admin

mongodb:
  uri: mongodb://10.17.154.252:27019?replicaSet=rs0
  db_name: workflow_db_dev
