#!/usr/bin/env bash
# One-command host deployment for DML V4 using uv (no containers).

set -Eeuo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEFAULT_CONFIG="$PROJECT_ROOT/config/config.yaml"
MANAGER="${DML_PROCESS_MANAGER:-auto}"
MANAGER_FILE="$PROJECT_ROOT/.deploy-manager"
ENV_FILE="$PROJECT_ROOT/.deploy.env"
API_SERVICE="dmlv4-backend.service"
WORKER_SERVICE="dmlv4-kafka-worker.service"
RUN_INIT=1
START_SERVICES=1
PRUNE_WORKFLOW=0

if [[ -f "$ENV_FILE" ]]; then
    persisted_config="$(
        set +u
        # This file is generated by write_runtime_env and is mode 0600.
        source "$ENV_FILE"
        printf '%s' "${CONFIG_PATH:-}"
    )"
    persisted_worker="$(
        set +u
        source "$ENV_FILE"
        printf '%s' "${DML_WITH_WORKER:-}"
    )"
    CONFIG_PATH="${CONFIG_PATH:-$persisted_config}"
    DML_WITH_WORKER="${DML_WITH_WORKER:-$persisted_worker}"
fi
CONFIG_FILE="${CONFIG_PATH:-$DEFAULT_CONFIG}"
WITH_WORKER="${DML_WITH_WORKER:-1}"

ACTION=install
if [[ $# -gt 0 && "$1" != -* ]]; then
    ACTION="$1"
    shift
fi

info() { printf '\033[0;32m[ok]\033[0m %s\n' "$1"; }
warn() { printf '\033[1;33m[!]\033[0m %s\n' "$1" >&2; }
die() { printf '\033[0;31m[x]\033[0m %s\n' "$1" >&2; exit 1; }

usage() {
    cat <<'EOF'
Usage: ./deploy.sh [action] [options]

Actions:
  install     Install/sync dependencies, initialize data and start services (default)
  update      Re-sync locked dependencies, initialize data and restart services
  init        Initialize MongoDB workflow data, indexes and RBAC roles
  start       Start API and Kafka worker
  stop        Stop API and Kafka worker
  restart     Restart API and Kafka worker
  status      Show service status
  doctor      Check uv, configuration, environment and process manager

Options:
  --config PATH              Use a specific YAML config file
  --manager auto|systemd|script
                             Use systemd on Linux when available, otherwise shell scripts
  --skip-init                Do not initialize MongoDB/RBAC during install or update
  --prune-workflow           Delete workflow records absent from JSON configuration
  --no-start                 Prepare the environment without starting services
  --without-worker           Do not install or manage the Kafka worker service
  -h, --help                 Show this help

Optional administrator creation (environment variables):
  DML_ADMIN_PASSWORD         Create/update an administrator when set
  DML_ADMIN_USER_ID          Default: admin
  DML_ADMIN_USERNAME         Default: 系统管理员
  DML_ADMIN_EMAIL            Optional email
EOF
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --config)
            [[ $# -ge 2 ]] || die "--config requires a path"
            CONFIG_FILE="$2"
            shift 2
            ;;
        --manager)
            [[ $# -ge 2 ]] || die "--manager requires a value"
            MANAGER="$2"
            shift 2
            ;;
        --skip-init) RUN_INIT=0; shift ;;
        --prune-workflow) PRUNE_WORKFLOW=1; shift ;;
        --no-start) START_SERVICES=0; shift ;;
        --without-worker) WITH_WORKER=0; shift ;;
        -h|--help) usage; exit 0 ;;
        *) die "Unknown option: $1" ;;
    esac
done

case "$MANAGER" in
    auto|systemd|script) ;;
    *) die "Unsupported process manager: $MANAGER" ;;
esac
case "$WITH_WORKER" in
    0|1) ;;
    *) die "DML_WITH_WORKER must be 0 or 1" ;;
esac
if [[ $PRUNE_WORKFLOW -eq 1 ]]; then
    case "$ACTION" in
        install|update|init) ;;
        *) die "--prune-workflow is only valid with install, update or init" ;;
    esac
    [[ $RUN_INIT -eq 1 ]] || die "--prune-workflow cannot be combined with --skip-init"
fi

if [[ "$CONFIG_FILE" != /* ]]; then
    CONFIG_FILE="$PROJECT_ROOT/$CONFIG_FILE"
fi

export DML_ENV=production
export CONFIG_PATH="$CONFIG_FILE"
export SKIP_INDEX_SYNC=1
export PYTHONUNBUFFERED=1

refresh_path() {
    export PATH="$HOME/.local/bin:$HOME/.cargo/bin:$PATH"
}

ensure_uv() {
    refresh_path
    if command -v uv >/dev/null 2>&1; then
        info "uv available: $(uv --version)"
        return
    fi

    command -v curl >/dev/null 2>&1 || die "uv and curl are unavailable; install uv first"
    warn "uv is not installed; downloading the official installer from astral.sh"
    local installer
    installer="$(mktemp)"
    curl -LsSf https://astral.sh/uv/install.sh -o "$installer"
    UV_NO_MODIFY_PATH=1 sh "$installer"
    rm -f "$installer"
    refresh_path
    command -v uv >/dev/null 2>&1 || die "uv installation completed but uv is not on PATH"
    info "uv installed: $(uv --version)"
}

prepare_config() {
    if [[ ! -f "$CONFIG_FILE" ]]; then
        if [[ "$CONFIG_FILE" != "$DEFAULT_CONFIG" ]]; then
            die "Config file does not exist: $CONFIG_FILE"
        fi
        cp "$PROJECT_ROOT/config/config.yaml.example" "$CONFIG_FILE"
        chmod 600 "$CONFIG_FILE"
        warn "Created $CONFIG_FILE from the template"
        warn "Edit infrastructure addresses and secrets, then run ./deploy.sh install again"
        exit 2
    fi
    chmod 600 "$CONFIG_FILE"
    info "Config ready: $CONFIG_FILE"
}

sync_dependencies() {
    ensure_uv
    cd "$PROJECT_ROOT"
    info "Synchronizing production dependencies from uv.lock"
    uv sync --frozen --no-dev --compile-bytecode
    [[ -x "$PROJECT_ROOT/.venv/bin/python" ]] || die "uv did not create .venv/bin/python"
}

validate_config() {
    local python="$PROJECT_ROOT/.venv/bin/python"
    [[ -x "$python" ]] || die "Python environment is missing; run ./deploy.sh install"
    DML_ENV=production CONFIG_PATH="$CONFIG_FILE" "$python" - <<'PY'
from urllib.parse import urlparse

from app.shared.config import get_settings

s = get_settings()
errors = []
warnings = []

if s.app.debug:
    errors.append("app.debug must be false in production")
if s.app.dev_bypass_auth:
    errors.append("app.dev_bypass_auth must be false in production")
if "*" in s.app.cors_origins:
    warnings.append("app.cors_origins contains '*'; restrict it when the frontend origin is known")

secret = s.jwt.secret_key.strip()
placeholders = {"change_me", "change-me", "replace-me", "your-secret-key"}
if len(secret) < 32 or secret.lower() in placeholders:
    errors.append("jwt.secret_key must be a non-placeholder value with at least 32 characters")
if s.rabbitmq.username == "guest" or s.rabbitmq.password == "guest":
    warnings.append("RabbitMQ still uses the guest credential")
if s.minio.access_key == "minioadmin" or s.minio.secret_key == "minioadmin":
    warnings.append("MinIO still uses the default credential")

mongo = urlparse(s.mongodb.uri)
mongo_host = mongo.hostname or "configured-host"
print(
    f"Configuration: service={s.app.service_name}, listen={s.app.host}:{s.app.port}, "
    f"mongo={mongo_host}/{s.mongodb.db_name}"
)
for warning in warnings:
    print(f"WARNING: {warning}")
if errors:
    for error in errors:
        print(f"ERROR: {error}")
    raise SystemExit(2)
PY
    info "Production configuration validated"
}

initialize_data() {
    local run=(uv run --frozen --no-dev --no-sync python)
    cd "$PROJECT_ROOT"
    info "Synchronizing MongoDB indexes for all document models"
    "${run[@]}" scripts/init/sync_indexes.py
    info "Synchronizing workflow configuration"
    local workflow_args=(scripts/init/sync_workflow.py)
    if [[ $PRUNE_WORKFLOW -eq 1 ]]; then
        workflow_args+=(--prune)
        warn "Workflow pruning is enabled"
    fi
    "${run[@]}" "${workflow_args[@]}"
    info "Synchronizing RBAC roles"
    "${run[@]}" scripts/init/sync_rbac.py

    if [[ -n "${DML_ADMIN_PASSWORD:-}" ]]; then
        local user_args=(
            scripts/init/create_user.py
            --user-id "${DML_ADMIN_USER_ID:-admin}"
            --username "${DML_ADMIN_USERNAME:-系统管理员}"
            --password-env DML_ADMIN_PASSWORD
            --roles ADMIN
            --upsert
        )
        if [[ -n "${DML_ADMIN_EMAIL:-}" ]]; then
            user_args+=(--email "$DML_ADMIN_EMAIL")
        fi
        "${run[@]}" "${user_args[@]}"
        info "Administrator synchronized"
    else
        warn "DML_ADMIN_PASSWORD is unset; administrator creation was skipped"
    fi
}

systemd_available() {
    command -v systemctl >/dev/null 2>&1 && [[ -d /run/systemd/system ]]
}

select_manager() {
    if [[ "$MANAGER" == "auto" && -f "$MANAGER_FILE" ]]; then
        MANAGER="$(<"$MANAGER_FILE")"
    fi
    if [[ "$MANAGER" == "auto" ]]; then
        if systemd_available; then
            MANAGER=systemd
        else
            MANAGER=script
        fi
    fi
    case "$MANAGER" in
        systemd|script) ;;
        *) die "Invalid saved process manager: $MANAGER" ;;
    esac
    if [[ "$MANAGER" == "systemd" ]] && ! systemd_available; then
        die "systemd is not running on this host; use --manager script"
    fi
}

write_runtime_env() {
    local escaped_config="${CONFIG_FILE//\\/\\\\}"
    escaped_config="${escaped_config//\"/\\\"}"
    cat > "$ENV_FILE" <<EOF
DML_ENV=production
CONFIG_PATH="$escaped_config"
DML_WITH_WORKER=$WITH_WORKER
SKIP_INDEX_SYNC=1
PYTHONUNBUFFERED=1
EOF
    chmod 600 "$ENV_FILE"
}

run_privileged() {
    if [[ ${EUID:-$(id -u)} -eq 0 ]]; then
        "$@"
    elif command -v sudo >/dev/null 2>&1; then
        sudo "$@"
    else
        die "Installing systemd services requires root or sudo; use --manager script"
    fi
}

install_systemd_units() {
    local service_user="${DML_SERVICE_USER:-${SUDO_USER:-$(id -un)}}"
    local service_group="${DML_SERVICE_GROUP:-$(id -gn "$service_user")}"
    local temp_dir
    temp_dir="$(mktemp -d)"
    write_runtime_env

    cat > "$temp_dir/$API_SERVICE" <<EOF
[Unit]
Description=DML V4 Backend API
Wants=network-online.target
After=network-online.target

[Service]
Type=simple
User=$service_user
Group=$service_group
WorkingDirectory="$PROJECT_ROOT"
EnvironmentFile="$ENV_FILE"
ExecStart="$PROJECT_ROOT/server.sh" run
Restart=on-failure
RestartSec=5
TimeoutStopSec=45
KillSignal=SIGTERM
NoNewPrivileges=true
PrivateTmp=true
UMask=0027

[Install]
WantedBy=multi-user.target
EOF

    cat > "$temp_dir/$WORKER_SERVICE" <<EOF
[Unit]
Description=DML V4 Kafka Worker
Wants=network-online.target
After=network-online.target $API_SERVICE

[Service]
Type=simple
User=$service_user
Group=$service_group
WorkingDirectory="$PROJECT_ROOT"
EnvironmentFile="$ENV_FILE"
ExecStart="$PROJECT_ROOT/kafka_worker.sh" run
Restart=on-failure
RestartSec=5
TimeoutStopSec=45
KillSignal=SIGTERM
NoNewPrivileges=true
PrivateTmp=true
UMask=0027

[Install]
WantedBy=multi-user.target
EOF

    run_privileged install -m 0644 "$temp_dir/$API_SERVICE" "/etc/systemd/system/$API_SERVICE"
    if [[ $WITH_WORKER -eq 1 ]]; then
        run_privileged install -m 0644 "$temp_dir/$WORKER_SERVICE" "/etc/systemd/system/$WORKER_SERVICE"
    fi
    run_privileged systemctl daemon-reload
    run_privileged systemctl enable "$API_SERVICE"
    if [[ $WITH_WORKER -eq 1 ]]; then
        run_privileged systemctl enable "$WORKER_SERVICE"
    fi
    rm -rf "$temp_dir"
    info "systemd units installed"
}

script_services() {
    local action="$1"
    if [[ "$action" == "start" || "$action" == "restart" ]]; then
        "$PROJECT_ROOT/server.sh" "$action"
        if [[ $WITH_WORKER -eq 1 ]]; then
            "$PROJECT_ROOT/kafka_worker.sh" "$action"
        fi
    elif [[ "$action" == "stop" ]]; then
        if [[ $WITH_WORKER -eq 1 ]]; then
            "$PROJECT_ROOT/kafka_worker.sh" stop
        fi
        "$PROJECT_ROOT/server.sh" stop
    else
        local result=0
        "$PROJECT_ROOT/server.sh" status || result=1
        if [[ $WITH_WORKER -eq 1 ]]; then
            "$PROJECT_ROOT/kafka_worker.sh" status || result=1
        fi
        return "$result"
    fi
}

systemd_services() {
    local action="$1"
    local services=("$API_SERVICE")
    if [[ $WITH_WORKER -eq 1 ]]; then
        services+=("$WORKER_SERVICE")
    fi
    if [[ "$action" == "status" ]]; then
        run_privileged systemctl --no-pager --full status "${services[@]}"
    else
        run_privileged systemctl "$action" "${services[@]}"
    fi
}

manage_services() {
    local action="$1"
    select_manager
    if [[ "$MANAGER" == "systemd" ]]; then
        systemd_services "$action"
    else
        script_services "$action"
    fi
}

wait_for_api() {
    local python="$PROJECT_ROOT/.venv/bin/python"
    DML_ENV=production CONFIG_PATH="$CONFIG_FILE" "$python" - <<'PY'
import time
import urllib.request

from app.shared.config import get_settings

port = get_settings().app.port
url = f"http://127.0.0.1:{port}/health/ready"
for _ in range(60):
    try:
        with urllib.request.urlopen(url, timeout=2) as response:
            if response.status == 200:
                print(f"Health check passed: {url}")
                raise SystemExit(0)
    except Exception:
        time.sleep(1)
print(f"Health check timed out: {url}")
raise SystemExit(1)
PY
}

verify_services() {
    select_manager
    if [[ "$MANAGER" == "systemd" ]]; then
        local services=("$API_SERVICE")
        if [[ $WITH_WORKER -eq 1 ]]; then
            services+=("$WORKER_SERVICE")
        fi
        run_privileged systemctl is-active --quiet "${services[@]}"
    else
        script_services status
    fi
    info "Managed services are running"
}

record_manager() {
    printf '%s\n' "$MANAGER" > "$MANAGER_FILE"
}

doctor() {
    local failed=0
    local config_ready=0
    refresh_path
    if command -v uv >/dev/null 2>&1; then
        info "$(uv --version)"
    else
        warn "uv is not installed"
        failed=1
    fi
    if [[ -f "$CONFIG_FILE" ]]; then
        info "Config exists: $CONFIG_FILE"
        config_ready=1
    else
        warn "Config is missing: $CONFIG_FILE"
        failed=1
    fi
    if [[ -x "$PROJECT_ROOT/.venv/bin/python" ]]; then
        info "Virtual environment: $PROJECT_ROOT/.venv"
        if [[ $config_ready -eq 1 ]]; then
            validate_config || failed=1
        fi
    else
        warn "Virtual environment is missing"
        failed=1
    fi
    select_manager
    info "Process manager: $MANAGER"
    bash -n "$PROJECT_ROOT/deploy.sh" "$PROJECT_ROOT/server.sh" "$PROJECT_ROOT/kafka_worker.sh"
    info "Shell syntax checks passed"
    return "$failed"
}

case "$ACTION" in
    install)
        prepare_config
        sync_dependencies
        validate_config
        if [[ $RUN_INIT -eq 1 ]]; then initialize_data; fi
        select_manager
        if [[ "$MANAGER" == "systemd" ]]; then install_systemd_units; fi
        if [[ "$MANAGER" == "script" ]]; then write_runtime_env; fi
        record_manager
        if [[ $START_SERVICES -eq 1 ]]; then
            manage_services start
            wait_for_api
            verify_services
        fi
        info "Deployment completed with process manager: $MANAGER"
        ;;
    update)
        prepare_config
        sync_dependencies
        validate_config
        if [[ $RUN_INIT -eq 1 ]]; then initialize_data; fi
        select_manager
        if [[ "$MANAGER" == "systemd" ]]; then install_systemd_units; fi
        if [[ "$MANAGER" == "script" ]]; then write_runtime_env; fi
        record_manager
        if [[ $START_SERVICES -eq 1 ]]; then
            manage_services restart
            wait_for_api
            verify_services
        fi
        info "Update completed"
        ;;
    init)
        prepare_config
        sync_dependencies
        validate_config
        initialize_data
        ;;
    start|stop|restart|status)
        manage_services "$ACTION"
        if [[ "$ACTION" == "start" || "$ACTION" == "restart" ]]; then
            wait_for_api
            verify_services
        fi
        ;;
    doctor) doctor ;;
    -h|--help|help) usage ;;
    *) usage; die "Unknown action: $ACTION" ;;
esac
