export const rdmStyles = {
  overlay: {
    position: 'fixed' as const,
    top: 0, left: 0, right: 0, bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.55)',
    backdropFilter: 'blur(4px)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2000,
  },
  modal: {
    backgroundColor: 'var(--bg-elevated)',
    borderRadius: '14px',
    width: '92%',
    maxWidth: '1200px',
    maxHeight: '92vh',
    display: 'flex',
    flexDirection: 'column' as const,
    boxShadow: '0 25px 80px rgba(0, 0, 0, 0.35)',
    border: '1px solid var(--border-default)',
  },

  // ── Header ──
  modalHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: '16px',
    padding: '18px 28px',
    borderBottom: '1px solid var(--border-default)',
    backgroundColor: 'var(--bg-tertiary)',
    borderRadius: '14px 14px 0 0',
  } as const,
  modalHeaderMain: {
    flex: 1,
    minWidth: 0,
  } as const,
  headerBadges: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    marginBottom: '6px',
    flexWrap: 'wrap' as const,
  } as const,
  headerBadge: {
    fontSize: '11px',
    padding: '2px 10px',
    borderRadius: '10px',
    fontWeight: 500,
  } as const,
  headerActions: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '12px',
    flexShrink: 0,
  } as const,
  reqId: {
    fontSize: '12px',
    color: 'var(--accent-cyan)',
    fontFamily: "'JetBrains Mono', monospace",
    fontWeight: 500,
  } as const,
  modalTitle: {
    margin: 0,
    fontSize: '20px',
    fontWeight: 600,
    color: 'var(--text-primary)',
    wordBreak: 'break-word' as const,
    lineHeight: 1.4,
  } as const,
  closeButton: {
    fontSize: '28px',
    color: 'var(--text-muted)',
    backgroundColor: 'transparent',
    border: 'none',
    cursor: 'pointer',
    padding: '0',
    lineHeight: 1,
  } as const,

  // ── Split body ──
  splitBody: {
    flex: 1,
    minHeight: 0,
    display: 'flex',
    overflow: 'hidden',
  } as const,

  // ── Left sidebar ──
  sidebar: {
    width: 300,
    minWidth: 300,
    overflowY: 'auto' as const,
    borderRight: '1px solid var(--border-subtle)',
    backgroundColor: 'var(--bg-primary)',
    padding: '20px 18px 28px',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '14px',
  } as const,
  sidePersonGroup: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '6px',
  } as const,
  sidePersonCard: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    padding: '8px 12px',
    backgroundColor: 'var(--surface-secondary)',
    borderRadius: '8px',
    border: '1px solid var(--border-muted)',
  } as const,
  sidePersonRole: {
    fontSize: '10px',
    fontWeight: 600,
    color: 'var(--text-tertiary)',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.4px',
    minWidth: 72,
    flexShrink: 0,
  } as const,
  sidePersonName: {
    fontSize: '13px',
    fontWeight: 600,
    color: 'var(--text-primary)',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
  } as const,
  sideDivider: {
    height: 1,
    backgroundColor: 'var(--border-subtle)',
  } as const,
  sideSection: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '8px',
  } as const,
  sideSectionTitle: {
    fontSize: '10px',
    fontWeight: 600,
    color: 'var(--text-tertiary)',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.6px',
  } as const,
  sideFieldValue: {
    fontSize: '13px',
    fontWeight: 500,
    color: 'var(--text-primary)',
    fontFamily: "'JetBrains Mono', monospace",
  } as const,
  sideVersionRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  } as const,
  sideVersionItem: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '2px',
  } as const,
  sideVersionLabel: {
    fontSize: '9px',
    fontWeight: 600,
    color: 'var(--text-tertiary)',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.4px',
  } as const,
  sideVersionValue: {
    fontSize: '13px',
    fontFamily: "'JetBrains Mono', monospace",
    color: 'var(--text-primary)',
    fontWeight: 500,
  } as const,
  sideVersionArrow: {
    color: 'var(--text-muted)',
    fontSize: '14px',
    marginBottom: 10,
  } as const,
  sideDateRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  } as const,
  sideDateLabel: {
    fontSize: '11px',
    fontWeight: 500,
    color: 'var(--text-secondary)',
  } as const,
  sideDateValue: {
    fontSize: '12px',
    fontFamily: "'JetBrains Mono', monospace",
    color: 'var(--text-primary)',
  } as const,
  sideMetaRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  } as const,
  sideMetaLabel: {
    fontSize: '10px',
    fontWeight: 600,
    color: 'var(--text-tertiary)',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.4px',
  } as const,
  sideMetaValue: {
    fontSize: '12px',
    color: 'var(--text-secondary)',
  } as const,
  sideMetaTime: {
    fontSize: '11px',
    fontFamily: "'JetBrains Mono', monospace",
    color: 'var(--text-secondary)',
  } as const,
  sideCountBadge: {
    fontSize: '12px',
    fontWeight: 600,
    padding: '2px 8px',
    borderRadius: '10px',
    backgroundColor: 'rgba(121, 192, 255, 0.15)',
    color: 'var(--accent-cyan)',
  } as const,
  sideMeta: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '6px',
  } as const,

  // ── Right main panel ──
  mainPanel: {
    flex: 1,
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column' as const,
    backgroundColor: 'var(--bg-elevated)',
  } as const,
  mainTagBar: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '8px',
    padding: '14px 24px 10px',
    borderBottom: '1px solid var(--border-subtle)',
    backgroundColor: 'var(--bg-primary)',
  } as const,
  mainTabBar: {
    display: 'flex',
    gap: 0,
    padding: '0 24px',
    borderBottom: '1px solid var(--border-subtle)',
    backgroundColor: 'var(--bg-elevated)',
    flexShrink: 0,
  } as const,
  mainTab: {
    padding: '12px 20px',
    border: 'none',
    background: 'transparent',
    color: 'var(--text-tertiary)',
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: 500,
    borderBottom: '2px solid transparent',
    marginBottom: -1,
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    transition: 'color var(--transition-fast), border-color var(--transition-fast)',
  } as const,
  mainTabActive: {
    color: 'var(--accent-primary)',
    borderBottom: '2px solid var(--accent-primary)',
    fontWeight: 600,
  } as const,
  mainTabBadge: {
    fontSize: '11px',
    fontWeight: 600,
    padding: '1px 8px',
    borderRadius: 'var(--radius-full)',
    backgroundColor: 'var(--surface-tertiary)',
    color: 'var(--text-secondary)',
  } as const,
  mainContent: {
    flex: 1,
    overflowY: 'auto' as const,
    padding: '20px 24px',
    minHeight: 0,
  } as const,

  // ── Right content: 描述 ──
  textBlock: {
    marginBottom: '20px',
  } as const,
  textBlockTitle: {
    display: 'block',
    fontSize: '11px',
    fontWeight: 600,
    color: 'var(--text-muted)',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.5px',
    marginBottom: '8px',
  } as const,
  textBlockContent: {
    fontSize: '13px',
    color: 'var(--text-primary)',
    whiteSpace: 'pre-wrap' as const,
    lineHeight: 1.7,
    padding: '14px',
    backgroundColor: 'var(--bg-secondary)',
    borderRadius: '8px',
    border: '1px solid var(--border-muted)',
  } as const,
  textBlockEmpty: {
    color: 'var(--text-muted)',
    fontStyle: 'italic' as const,
  } as const,

  // ── Right content: 组件与参数 ──
  componentSection: {
    marginBottom: '20px',
  } as const,
  subTitle: {
    display: 'block',
    fontSize: '11px',
    fontWeight: 600,
    color: 'var(--text-muted)',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.5px',
    marginBottom: '8px',
  } as const,
  tagList: {
    display: 'flex',
    flexWrap: 'wrap' as const,
    gap: '6px',
  } as const,
  compTag: {
    fontSize: '12px',
    color: 'var(--accent-green)',
    backgroundColor: 'rgba(63, 185, 80, 0.15)',
    padding: '4px 12px',
    borderRadius: '12px',
    fontWeight: 500,
  } as const,
  tag: {
    fontSize: '12px',
    color: 'var(--accent-blue)',
    backgroundColor: 'rgba(88, 166, 255, 0.15)',
    padding: '3px 10px',
    borderRadius: '12px',
  } as const,
  paramsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: '10px',
  } as const,
  paramCard: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '4px',
    padding: '10px 14px',
    backgroundColor: 'var(--bg-secondary)',
    borderRadius: '8px',
    border: '1px solid var(--border-muted)',
  } as const,
  paramName: {
    fontSize: '12px',
    fontWeight: 600,
    fontFamily: "'JetBrains Mono', monospace",
    color: 'var(--accent-purple)',
  } as const,
  paramValue: {
    fontSize: '12px',
    fontFamily: "'JetBrains Mono', monospace",
    color: 'var(--text-primary)',
    wordBreak: 'break-all' as const,
  } as const,
  emptyHint: {
    fontSize: '13px',
    color: 'var(--text-muted)',
    textAlign: 'center' as const,
    padding: '32px 16px',
    margin: 0,
  } as const,

  // ── Right content: 附件 ──
  attachmentGrid: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '8px',
  } as const,
  attachmentCard: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '10px 12px',
    backgroundColor: 'var(--bg-secondary)',
    borderRadius: '8px',
    border: '1px solid var(--border-muted)',
  } as const,
  attachThumbLink: {
    flexShrink: 0,
  } as const,
  attachThumb: {
    width: '48px',
    height: '48px',
    objectFit: 'cover' as const,
    borderRadius: '4px',
    border: '1px solid var(--border-muted)',
  } as const,
  attachInfo: {
    flex: 1,
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '4px',
  } as const,
  attachName: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
  } as const,
  attachIcon: {
    fontSize: '16px',
    flexShrink: 0,
  } as const,
  attachLink: {
    fontSize: '13px',
    color: 'var(--accent-blue)',
    textDecoration: 'none',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
  } as const,
  attachNameText: {
    fontSize: '13px',
    color: 'var(--text-primary)',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
  } as const,
  attachMeta: {
    display: 'flex',
    flexWrap: 'wrap' as const,
    gap: '8px',
    fontSize: '11px',
    color: 'var(--text-muted)',
  } as const,
  attachDownloadBtn: {
    flexShrink: 0,
    fontSize: '16px',
    color: 'var(--text-muted)',
    textDecoration: 'none',
    padding: '4px 6px',
    borderRadius: '4px',
    cursor: 'pointer',
  } as const,
};
