import type { CSSProperties } from 'react';

export const rlmStyles: Record<string, CSSProperties> = {
  errorBanner: {
    marginBottom: 'var(--space-4)',
  },
  errorClose: {
    marginLeft: 'auto',
    padding: '0 8px',
    fontSize: '18px',
    background: 'none',
    border: 'none',
    color: 'var(--status-error)',
    cursor: 'pointer',
  },
  colCheck: { width: '44px' },
  colCount: { width: '80px', textAlign: 'center' as const },
  colType: { width: '90px' },
  colActions: { width: '140px' },
  checkbox: {
    width: '16px',
    height: '16px',
    cursor: 'pointer',
    accentColor: 'var(--accent-primary)',
  },
  roleNameCell: {
    fontWeight: 600,
    color: 'var(--text-primary)',
  },
  roleIdCell: {
    display: 'block',
    fontSize: '11px',
    color: 'var(--text-tertiary)',
    marginTop: '2px',
  },
  detailPanel: {
    display: 'flex',
    flexDirection: 'column' as const,
    height: '100%',
    minHeight: 0,
  },
  detailHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 'var(--space-4)',
    marginBottom: 'var(--space-4)',
    paddingBottom: 'var(--space-4)',
    borderBottom: '1px solid var(--border-subtle)',
  },
  detailTitle: {
    margin: 0,
    fontSize: '18px',
    fontWeight: 600,
    color: 'var(--text-primary)',
  },
  descCell: {
    fontSize: '13px',
    color: 'var(--text-secondary)',
    maxWidth: '280px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
    display: 'block',
  },
  permCountBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: '28px',
    padding: '2px 8px',
    fontSize: '12px',
    fontWeight: 600,
    color: 'var(--text-secondary)',
    backgroundColor: 'var(--surface-tertiary)',
    borderRadius: 'var(--radius-full)',
  },
  rowActions: {
    display: 'flex',
    gap: '4px',
  },
  roleModal: {
    width: '960px',
    maxWidth: '94vw',
    maxHeight: '88vh',
    display: 'flex',
    flexDirection: 'column' as const,
  },
  modalHeader: {
    borderBottom: '1px solid var(--border-subtle)',
  },
  modalSubtitle: {
    fontSize: '12px',
    color: 'var(--text-tertiary)',
    marginTop: '2px',
    display: 'block',
  },
  modalBody: {
    flex: 1,
    minHeight: 0,
    overflow: 'hidden',
    padding: 'var(--space-5) var(--space-6)',
    display: 'flex',
    flexDirection: 'column' as const,
  },
  twoCol: {
    display: 'grid',
    gridTemplateColumns: '260px 1fr',
    gridTemplateRows: 'minmax(0, 1fr)',
    gap: 'var(--space-6)',
    alignItems: 'stretch',
    flex: 1,
    minHeight: 0,
    overflow: 'hidden',
  },
  basicInfoSection: {
    marginBottom: 0,
    overflowY: 'auto' as const,
    minHeight: 0,
  },
  permSection: {
    display: 'flex',
    flexDirection: 'column' as const,
    minHeight: 0,
    minWidth: 0,
    overflow: 'hidden',
  },
  permToolbar: {
    flexShrink: 0,
    backgroundColor: 'var(--surface-primary)',
    paddingBottom: 'var(--space-3)',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 'var(--space-3)',
    borderBottom: '1px solid var(--border-subtle)',
    marginBottom: 'var(--space-3)',
  },
  permScrollArea: {
    flex: 1,
    minHeight: 0,
    overflowY: 'auto' as const,
    paddingRight: 'var(--space-1)',
  },
  sectionHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 'var(--space-3)',
  },
  sectionTitle: {
    margin: 0,
    fontSize: '13px',
    fontWeight: 600,
    color: 'var(--text-secondary)',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
  },
  permSelectedBadge: {
    marginLeft: '8px',
    padding: '2px 8px',
    fontSize: '11px',
    fontWeight: 600,
    color: 'var(--accent-primary)',
    backgroundColor: 'rgba(22, 163, 74, 0.1)',
    borderRadius: 'var(--radius-full)',
    textTransform: 'none',
    letterSpacing: 0,
  },
  permSelectedSummary: {
    display: 'flex',
    flexWrap: 'wrap' as const,
    gap: '6px',
    maxHeight: '56px',
    overflowY: 'auto' as const,
  },
  permChip: {
    display: 'inline-flex',
    alignItems: 'center',
    padding: '2px 8px',
    fontSize: '11px',
    fontWeight: 500,
    color: 'var(--text-primary)',
    backgroundColor: 'var(--surface-tertiary)',
    borderRadius: 'var(--radius-full)',
    whiteSpace: 'nowrap' as const,
  },
  formGroup: {
    marginBottom: 'var(--space-4)',
  },
  label: {
    display: 'block',
    fontSize: '13px',
    fontWeight: 500,
    color: 'var(--text-secondary)',
    marginBottom: '6px',
  },
  textarea: {
    resize: 'vertical' as const,
    minHeight: '72px',
  },
  systemHint: {
    fontSize: '12px',
    color: 'var(--text-tertiary)',
    margin: 0,
  },
  permGroupList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 'var(--space-3)',
    paddingBottom: 'var(--space-2)',
  },
  permGroup: {
    border: '1px solid var(--border-subtle)',
    borderRadius: 'var(--radius-lg)',
    backgroundColor: 'var(--surface-secondary)',
  },
  permGroupHeader: {
    padding: 'var(--space-3) var(--space-4)',
    backgroundColor: 'var(--surface-secondary)',
    borderBottom: '1px solid var(--border-subtle)',
  },
  permGroupLabel: {
    display: 'flex',
    alignItems: 'center',
    gap: 'var(--space-2)',
    cursor: 'pointer',
  },
  permGroupName: {
    fontSize: '13px',
    fontWeight: 600,
    color: 'var(--text-primary)',
    textTransform: 'capitalize',
  },
  permGroupCount: {
    marginLeft: 'auto',
    fontSize: '11px',
    color: 'var(--text-tertiary)',
  },
  permTileGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(148px, 1fr))',
    gap: 'var(--space-2)',
    padding: 'var(--space-3)',
  },
  permTile: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'flex-start',
    gap: '4px',
    padding: 'var(--space-2) var(--space-3)',
    border: '1px solid var(--border-subtle)',
    borderRadius: 'var(--radius-md)',
    backgroundColor: 'var(--surface-primary)',
    cursor: 'pointer',
    transition: 'background-color var(--transition-fast), border-color var(--transition-fast)',
    minWidth: 0,
  },
  permTileSelected: {
    backgroundColor: 'rgba(22, 163, 74, 0.08)',
    border: '1px solid var(--accent-primary)',
  },
  permTileName: {
    fontSize: '12px',
    fontWeight: 600,
    color: 'var(--text-primary)',
    lineHeight: 1.3,
    wordBreak: 'break-word' as const,
  },
  permTileCode: {
    fontSize: '10px',
    color: 'var(--text-tertiary)',
    lineHeight: 1.2,
    wordBreak: 'break-all' as const,
  },
  noResults: {
    fontSize: '13px',
    color: 'var(--text-tertiary)',
    textAlign: 'center' as const,
    padding: 'var(--space-6)',
  },
  confirmText: {
    fontSize: '14px',
    color: 'var(--text-primary)',
    margin: 0,
    lineHeight: 1.6,
  },
};
