import type { CSSProperties } from 'react';

/** Shared test case board UI tokens — B2B test tool aesthetic */
export const boardStyles = {
  /* ── Layout ── */
  pageWrap: {
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
  } satisfies CSSProperties,

  /* ── Hero / Summary ── */
  hero: {
    position: 'relative',
    borderRadius: 'var(--radius-xl)',
    padding: 'var(--space-5) var(--space-6)',
    marginBottom: 'var(--space-6)',
    overflow: 'hidden',
    background: 'linear-gradient(135deg, #eff6ff 0%, #f0f9ff 45%, #ecfeff 100%)',
    border: '1px solid color-mix(in srgb, #2563eb 15%, var(--border-subtle))',
  } satisfies CSSProperties,
  heroGlow: {
    position: 'absolute',
    top: -40,
    right: -20,
    width: 220,
    height: 220,
    borderRadius: '50%',
    background: 'radial-gradient(circle, rgba(37,99,235,0.18) 0%, transparent 70%)',
    pointerEvents: 'none',
  } satisfies CSSProperties,
  heroContent: { position: 'relative', zIndex: 1 } satisfies CSSProperties,
  heroBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    padding: '4px 12px',
    marginBottom: 'var(--space-3)',
    fontSize: 12,
    fontWeight: 600,
    color: '#2563eb',
    backgroundColor: 'rgba(37,99,235,0.10)',
    borderRadius: 'var(--radius-full)',
    border: '1px solid rgba(37,99,235,0.20)',
  } satisfies CSSProperties,
  heroTitle: {
    margin: '0 0 4px',
    fontSize: 22,
    fontWeight: 700,
    color: 'var(--text-primary)',
    letterSpacing: '-0.3px',
  } satisfies CSSProperties,
  heroDesc: {
    margin: 0,
    fontSize: 13,
    color: 'var(--text-secondary)',
    lineHeight: 1.5,
  } satisfies CSSProperties,
  heroStats: {
    display: 'flex',
    gap: 'var(--space-6)',
    marginTop: 'var(--space-4)',
    flexWrap: 'wrap',
  } satisfies CSSProperties,
  heroStatItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
  } satisfies CSSProperties,
  heroStatValue: {
    fontSize: 26,
    fontWeight: 700,
    fontFamily: "'JetBrains Mono', monospace",
    color: 'var(--text-primary)',
    letterSpacing: '-0.5px',
  } satisfies CSSProperties,
  heroStatLabel: {
    fontSize: 12,
    color: 'var(--text-tertiary)',
  } satisfies CSSProperties,
  heroStatDivider: {
    width: 1,
    height: 24,
    backgroundColor: 'var(--border-subtle)',
  } satisfies CSSProperties,

  /* ── Filter Bar ── */
  filterBar: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 'var(--space-3)',
    marginBottom: 'var(--space-4)',
  } satisfies CSSProperties,
  filterLeft: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 'var(--space-2)',
    flex: '1 1 auto',
  } satisfies CSSProperties,
  filterRight: {
    display: 'flex',
    alignItems: 'center',
    gap: 'var(--space-2)',
    flexShrink: 0,
    marginLeft: 'auto',
  } satisfies CSSProperties,
  searchInput: {
    width: 200,
    fontSize: 13,
  } satisfies CSSProperties,
  frameworkChips: {
    display: 'flex',
    gap: 4,
    marginBottom: 'var(--space-3)',
    flexShrink: 0,
    flexWrap: 'wrap',
  } satisfies CSSProperties,
  frameworkChip: {
    fontSize: 11,
    padding: '3px 10px',
    border: 'none',
    borderRadius: 12,
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: 3,
  } satisfies CSSProperties,

  /* ── Bulk Action Bar ── */
  bulkBar: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '4px 12px',
    background: 'color-mix(in srgb, var(--accent-blue) 8%, transparent)',
    borderRadius: 8,
    border: '1px solid color-mix(in srgb, var(--accent-blue) 18%, transparent)',
  } satisfies CSSProperties,
  bulkLabel: {
    fontSize: 13,
    fontWeight: 500,
    color: 'var(--accent-blue)',
  } satisfies CSSProperties,

  /* ── Detail Panel ── */
  detailHeader: {
    padding: '16px 24px 12px',
    borderBottom: '1px solid var(--border-subtle)',
  } satisfies CSSProperties,
  detailHeaderMeta: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    marginBottom: 6,
    flexWrap: 'wrap',
  } satisfies CSSProperties,
  detailTitle: {
    margin: 0,
    fontSize: 18,
    fontWeight: 600,
    color: 'var(--text-primary)',
  } satisfies CSSProperties,
  detailTabBar: {
    display: 'flex',
    gap: 0,
    padding: '0 24px',
    borderBottom: '1px solid var(--border-subtle)',
    flexShrink: 0,
  } satisfies CSSProperties,
  detailTab: (active: boolean): CSSProperties => ({
    padding: '10px 18px',
    border: 'none',
    background: 'transparent',
    color: active ? 'var(--accent-primary)' : 'var(--text-tertiary)',
    cursor: 'pointer',
    fontSize: 13,
    fontWeight: active ? 600 : 500,
    borderBottom: `2px solid ${active ? 'var(--accent-primary)' : 'transparent'}`,
    marginBottom: -1,
    transition: 'color 0.15s',
  }),
  detailBody: {
    flex: 1,
    overflowY: 'auto',
    padding: '20px 24px',
    minHeight: 0,
  } satisfies CSSProperties,

  /* ── Kanban ── */
  kanbanWrap: {
    flex: 1,
    display: 'flex',
    gap: 'var(--space-3)',
    overflowX: 'auto',
    padding: 'var(--space-3)',
    minHeight: 0,
  } satisfies CSSProperties,
  kanbanColumn: {
    minWidth: 240,
    maxWidth: 300,
    flexShrink: 0,
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: 'var(--surface-secondary)',
    borderRadius: 'var(--radius-lg)',
    border: '1px solid var(--border-subtle)',
    overflow: 'hidden',
  } satisfies CSSProperties,
  kanbanColumnHead: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 'var(--space-3) var(--space-3)',
    borderBottom: '1px solid var(--border-subtle)',
    backgroundColor: 'var(--surface-primary)',
    flexShrink: 0,
  } satisfies CSSProperties,
  kanbanColumnTitle: {
    fontSize: 12,
    fontWeight: 600,
    display: 'flex',
    alignItems: 'center',
    gap: 6,
  } satisfies CSSProperties,
  kanbanColumnCount: {
    fontSize: 11,
    fontFamily: "'JetBrains Mono', monospace",
    color: 'var(--text-tertiary)',
    padding: '1px 7px',
    borderRadius: 'var(--radius-full)',
    backgroundColor: 'var(--surface-tertiary)',
  } satisfies CSSProperties,
  kanbanBody: {
    flex: 1,
    overflowY: 'auto',
    padding: 'var(--space-2)',
    display: 'flex',
    flexDirection: 'column',
    gap: 'var(--space-2)',
  } satisfies CSSProperties,
  kanbanCard: {
    padding: 'var(--space-3)',
    backgroundColor: 'var(--surface-primary)',
    borderRadius: 'var(--radius-md)',
    border: '1px solid var(--border-subtle)',
    cursor: 'pointer',
    transition: 'border-color var(--transition-fast), box-shadow var(--transition-fast)',
  } satisfies CSSProperties,
  kanbanCardTitle: {
    fontSize: 13,
    fontWeight: 500,
    color: 'var(--text-primary)',
    lineHeight: 1.4,
    marginBottom: 'var(--space-1)',
  } satisfies CSSProperties,
  kanbanCardMeta: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    flexWrap: 'wrap',
  } satisfies CSSProperties,

  /* ── Shared view toggle ── */
  viewToggle: {
    display: 'flex',
    gap: 2,
    padding: 2,
    backgroundColor: 'var(--surface-secondary)',
    borderRadius: 'var(--radius-md)',
    border: '1px solid var(--border-subtle)',
  } satisfies CSSProperties,
  viewToggleBtn: (active: boolean): CSSProperties => ({
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 28,
    height: 26,
    border: 'none',
    borderRadius: 'var(--radius-sm)',
    background: active ? 'var(--surface-primary)' : 'transparent',
    color: active ? 'var(--accent-primary)' : 'var(--text-tertiary)',
    cursor: 'pointer',
    boxShadow: active ? 'var(--shadow-xs)' : 'none',
    fontWeight: active ? 600 : 400,
    fontSize: 12,
  }),

  /* ── Misc shared ── */
  grid2: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: '12px',
  } satisfies CSSProperties,
  miniLabel: {
    display: 'block',
    fontSize: 10,
    fontWeight: 600,
    color: 'var(--text-tertiary)',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.4px',
  } satisfies CSSProperties,
  relationChain: {
    display: 'flex',
    alignItems: 'center',
    gap: 16,
    flexWrap: 'wrap' as const,
  } satisfies CSSProperties,
  relationNode: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    padding: '12px 16px',
    background: 'var(--bg-secondary)',
    borderRadius: 10,
    border: '1px solid var(--border-muted)',
    minWidth: 140,
  } satisfies CSSProperties,
  relationIcon: { fontSize: 20 } satisfies CSSProperties,
  relationLabel: {
    display: 'block',
    fontSize: 10,
    fontWeight: 600,
    color: 'var(--text-tertiary)',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.4px',
  } satisfies CSSProperties,
  relationValue: {
    fontSize: 13,
    fontWeight: 500,
    fontFamily: "'JetBrains Mono', monospace",
    color: 'var(--text-primary)',
  } satisfies CSSProperties,
  relationArrow: { fontSize: 18, color: 'var(--text-tertiary)' } satisfies CSSProperties,

  /* ── Tags / badges ── */
  tagPill: {
    fontSize: 11,
    padding: '3px 10px',
    borderRadius: 12,
    background: 'rgba(88,166,255,0.15)',
    color: '#58a6ff',
  } satisfies CSSProperties,
  typeBadge: (isManual: boolean): CSSProperties => ({
    fontSize: 10,
    padding: '1px 7px',
    borderRadius: 4,
    fontWeight: 600,
    whiteSpace: 'nowrap',
    background: isManual ? 'rgba(163,113,247,0.15)' : 'rgba(57,208,214,0.15)',
    color: isManual ? '#a371f7' : '#39d0d6',
  }),
  frameworkTag: (color: string): CSSProperties => ({
    fontSize: 10,
    padding: '1px 6px',
    borderRadius: 4,
    background: `${color}18`,
    color,
    fontWeight: 600,
    whiteSpace: 'nowrap',
  }),
  statusDot: (color: string): CSSProperties => ({
    width: 6,
    height: 6,
    borderRadius: '50%',
    background: color,
    flexShrink: 0,
  }),
  idTag: {
    fontSize: 10,
    fontFamily: "'JetBrains Mono', monospace",
    color: 'var(--text-tertiary)',
    marginLeft: 'auto',
  } satisfies CSSProperties,

  /* ── Case list item ── */
  listItem: (selected: boolean): CSSProperties => ({
    padding: '8px 12px',
    cursor: 'pointer',
    borderLeft: `2px solid ${selected ? 'var(--accent-primary)' : 'transparent'}`,
    backgroundColor: selected ? 'color-mix(in srgb, var(--accent-primary) 6%, transparent)' : undefined,
    borderBottom: '0.5px solid var(--border-subtle)',
    transition: 'background-color 0.1s',
  }),
  listItemRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  } satisfies CSSProperties,
  listItemMeta: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    marginTop: 4,
    marginLeft: 22,
  } satisfies CSSProperties,
};
