import type { CSSProperties } from 'react';

/** Shared catalog UI tokens — B2B test tool aesthetic */
export const catalogStyles = {
  card: {
    border: '1px solid var(--border-subtle)',
    borderRadius: 'var(--radius-lg)',
    backgroundColor: 'var(--surface-primary)',
    boxShadow: 'var(--shadow-sm)',
  } satisfies CSSProperties,
  cardInset: {
    backgroundColor: 'var(--surface-secondary)',
    borderRadius: 'var(--radius-md)',
    border: '1px solid var(--border-subtle)',
  } satisfies CSSProperties,
  labelCaps: {
    fontSize: 11,
    fontWeight: 600,
    color: 'var(--text-tertiary)',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.45px',
  } satisfies CSSProperties,
  chip: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 4,
    padding: '4px 10px',
    fontSize: 12,
    fontWeight: 500,
    color: 'var(--text-primary)',
    backgroundColor: 'var(--surface-secondary)',
    border: '1px solid var(--border-default)',
    borderRadius: 'var(--radius-full)',
    lineHeight: 1.3,
  } satisfies CSSProperties,
  chipLab: {
    backgroundColor: 'var(--status-info-bg)',
    borderColor: 'var(--accent-primary)',
    color: 'var(--accent-primary)',
    fontWeight: 600,
  } satisfies CSSProperties,
  chipLocked: {
    opacity: 0.92,
    cursor: 'default',
  } satisfies CSSProperties,
  chipRemove: {
    border: 'none',
    background: 'none',
    cursor: 'pointer',
    color: 'var(--text-tertiary)',
    fontSize: 14,
    lineHeight: 1,
    padding: 0,
    marginLeft: 2,
    borderRadius: 'var(--radius-sm)',
  } satisfies CSSProperties,
  previewBar: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 'var(--space-2)',
    padding: 'var(--space-3) var(--space-4)',
    backgroundColor: 'var(--surface-secondary)',
    border: '1px solid var(--border-subtle)',
    borderRadius: 'var(--radius-md)',
  } satisfies CSSProperties,
  previewBarActive: {
    backgroundColor: 'var(--status-info-bg)',
    borderColor: 'color-mix(in srgb, var(--accent-primary) 35%, var(--border-subtle))',
  } satisfies CSSProperties,
  suggestionPanel: {
    position: 'absolute' as const,
    top: '100%',
    left: 0,
    right: 0,
    marginTop: 4,
    maxHeight: 200,
    overflowY: 'auto' as const,
    backgroundColor: 'var(--surface-primary)',
    border: '1px solid var(--border-default)',
    borderRadius: 'var(--radius-md)',
    boxShadow: 'var(--shadow-md)',
    zIndex: 20,
  } satisfies CSSProperties,
  suggestionItem: {
    display: 'block',
    width: '100%',
    textAlign: 'left' as const,
    padding: '8px 12px',
    fontSize: 13,
    border: 'none',
    background: 'transparent',
    color: 'var(--text-primary)',
    cursor: 'pointer',
  } satisfies CSSProperties,
  sidebar: {
    width: 260,
    flexShrink: 0,
    borderRight: '1px solid var(--border-subtle)',
    padding: 'var(--space-4)',
    overflow: 'auto',
    backgroundColor: 'var(--surface-secondary)',
    boxShadow: 'inset -1px 0 0 var(--border-subtle)',
  } satisfies CSSProperties,
  treeNode: {
    display: 'flex',
    alignItems: 'center',
    gap: 2,
    borderRadius: 'var(--radius-md)',
    transition: 'background-color var(--transition-fast)',
  } satisfies CSSProperties,
  treeNodeSelected: {
    backgroundColor: 'color-mix(in srgb, var(--accent-primary) 12%, transparent)',
  } satisfies CSSProperties,
  treeNodeHover: {
    backgroundColor: 'var(--surface-hover)',
  } satisfies CSSProperties,
  breadcrumbBar: {
    display: 'flex',
    alignItems: 'center',
    flexWrap: 'wrap' as const,
    gap: 'var(--space-2)',
    marginBottom: 'var(--space-4)',
    padding: 'var(--space-3) var(--space-4)',
    backgroundColor: 'var(--surface-primary)',
    border: '1px solid var(--border-subtle)',
    borderRadius: 'var(--radius-lg)',
    boxShadow: 'var(--shadow-sm)',
    fontSize: 13,
    color: 'var(--text-secondary)',
  } satisfies CSSProperties,
};
