"""执行模块状态常量。"""

FINAL_CASE_STATUSES = {"PASSED", "FAILED", "SKIPPED"}
FINAL_TASK_STATUSES = {"PASSED", "FAILED", "SKIPPED", "CANCELLED"}

DEFAULT_EXECUTION_REPO_URL = "http://10.17.55.151:6600/litaiqing/bmc-case.git"
DEFAULT_EXECUTION_BRANCH = "master"
