"""执行模块状态常量。"""

FINAL_CASE_STATUSES = {"PASSED", "FAILED", "SKIPPED"}
FINAL_TASK_STATUSES = {"PASSED", "FAILED", "SKIPPED", "CANCELLED", "STOPPED"}
STOP_MODE_NONE = "NONE"
STOP_MODE_AFTER_CURRENT_CASE = "STOP_AFTER_CURRENT_CASE"
