"""系统运行配置的中文展示元数据。"""

RUNTIME_CONFIG_DESCRIPTIONS: dict[str, str] = {
    "rabbitmq.host": "RabbitMQ 服务地址",
    "rabbitmq.port": "RabbitMQ 服务端口",
    "rabbitmq.username": "RabbitMQ 用户名",
    "rabbitmq.password": "RabbitMQ 密码",
    "rabbitmq.virtual_host": "RabbitMQ 虚拟主机",
    "rabbitmq.heartbeat": "RabbitMQ 心跳间隔（秒）",
    "rabbitmq.blocked_connection_timeout": "RabbitMQ 连接阻塞超时（秒）",
    "rabbitmq.connection_attempts": "RabbitMQ 连接重试次数",
    "rabbitmq.retry_delay": "RabbitMQ 重试间隔（秒）",
    "rabbitmq.ssl_enabled": "是否启用 RabbitMQ SSL",
    "rabbitmq.task_queue": "任务下发队列名称",
    "rabbitmq.task_exchange": "任务交换机名称",
    "rabbitmq.task_routing_key": "任务路由键",
    "rabbitmq.dead_letter_exchange": "死信交换机名称",
    "rabbitmq.dead_letter_routing_key": "死信路由键",
    "rabbitmq.prefetch_count": "消费者预取消息数量",
    "kafka.bootstrap_servers": "Kafka 服务地址列表",
    "kafka.client_id": "Kafka 客户端标识",
    "kafka.result_topic": "执行结果主题名称",
    "kafka.dead_letter_topic": "死信主题名称",
    "kafka.test_events_topic": "测试事件主题名称",
    "kafka.execution_result_group_id": "执行结果消费者组标识",
    "kafka.test_events_group_id": "测试事件消费者组标识",
    "kafka.producer_options.acks": "生产者消息确认机制",
    "kafka.producer_options.retries": "生产者发送重试次数",
    "kafka.producer_options.batch_size": "生产者批次大小（字节）",
    "kafka.producer_options.linger_ms": "生产者批次等待时间（毫秒）",
    "kafka.consumer_options.auto_offset_reset": "消费者无偏移量时的起始策略",
    "kafka.consumer_options.enable_auto_commit": "消费者是否自动提交偏移量",
    "kafka.consumer_options.session_timeout_ms": "消费者会话超时（毫秒）",
    "kafka.consumer_options.heartbeat_interval_ms": "消费者心跳间隔（毫秒）",
    "kafka.consumer_options.max_poll_records": "单次拉取最大消息数",
    "kafka.consumer_options.consumer_timeout_ms": "消费者拉取超时（毫秒）",
    "minio.endpoint": "MinIO 服务地址",
    "minio.access_key": "MinIO 访问密钥",
    "minio.secret_key": "MinIO 私密密钥",
    "minio.bucket": "MinIO 存储桶名称",
    "minio.secure": "是否使用 HTTPS 连接 MinIO",
    "minio.presigned_url_expires_seconds": "预签名下载地址有效期（秒）",
    "jwt.secret_key": "用户令牌签名密钥",
    "jwt.algorithm": "用户令牌签名算法",
    "jwt.expire_minutes": "用户令牌有效期（分钟）",
    "jwt.issuer": "用户令牌签发方",
    "jwt.audience": "用户令牌接收方",
    "execution.scheduler_interval_sec": "定时任务扫描间隔（秒）",
    "execution.default_repo_url": "默认自动化代码仓库地址",
    "execution.kafka_worker_agent_id": "Kafka Worker 代理标识",
    "execution.kafka_worker_heartbeat_ttl_sec": "Kafka Worker 心跳有效期（秒）",
    "execution.kafka_worker_heartbeat_interval_sec": "Kafka Worker 心跳间隔（秒）",
    "redis.sentinel_hosts": "Redis Sentinel 地址列表",
    "redis.master_name": "Redis 主节点名称",
    "redis.username": "Redis 用户名",
    "redis.password": "Redis 密码",
    "redis.db": "Redis 数据库编号",
    "redis.socket_timeout": "Redis 操作超时（秒）",
    "redis.max_connections": "Redis 最大连接数",
    "redis.protocol": "Redis 通信协议版本",
    "redis.retry_on_timeout": "Redis 超时后是否重试",
    "redis.sentinel_socket_timeout": "Redis Sentinel 连接超时（秒）",
    "redis.service_registry_key": "Redis 服务注册键",
    "notification.enabled": "是否启用通知",
    "notification.batch_window_seconds": "通知合并窗口（秒）",
    "notification.max_detail_items": "单条通知最大明细数量",
    "notification.guangquan.api_url": "光圈通知接口地址",
    "notification.guangquan.component_name": "光圈通知组件名称",
    "notification.guangquan.timeout_sec": "光圈通知请求超时（秒）",
    "open_platform_gateway_jwt.enabled": "是否启用开放平台网关令牌",
    "open_platform_gateway_jwt.secret_key": "开放平台网关令牌签名密钥",
    "open_platform_gateway_jwt.algorithm": "开放平台网关令牌签名算法",
    "open_platform_gateway_jwt.issuer": "开放平台网关令牌签发方",
    "open_platform_gateway_jwt.audience": "开放平台网关令牌接收方",
    "open_platform_gateway_jwt.required_token_use": "开放平台网关令牌用途标识",
}
